### ISSUE TITLE
Echelon fails to build with hdf 1.10

### ISSUE THREAD

**Issue by shermanns** [qbb-project/echelon#46]
Due to the API change 1.8 -> 1.10 H5Rdereference was renamed to H5Rdereference1, and a new version H5Rdereference2 was introduced as default which additionally takes an an object access property list identifier. Changing H5Rdereference --> H5Rdereference1 solves it for now, but probably it is better to use the new API.

**Comment by chinz07** [comment]
Thx. This should be fixed by pull request #47.

For now, I will leave the old interface in place since we still need to support HDF5 1.8. Support for the old interface and file format wil be deprecated in version 0.8.0 und removed in version 0.9.0. I have opened issue #48 as a reminder.
